# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kj < Formula
  desc "Edit and create Kubernetes job from cronjob template using your EDITOR"
  homepage "https://github.com/kitagry/kj"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kitagry/kj/releases/download/0.3.1/kj_0.3.1_darwin_amd64.tar.gz"
      sha256 "5a041b24a9bacfdf61477eb78a059eeee0f450437a2cbb0b9c7666f2dfd440ec"

      def install
        bin.install "kj"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kitagry/kj/releases/download/0.3.1/kj_0.3.1_darwin_arm64.tar.gz"
      sha256 "a3f84512cb7d8a70a52716273e782583355135f83056288b76b641b8a2f460e4"

      def install
        bin.install "kj"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kitagry/kj/releases/download/0.3.1/kj_0.3.1_linux_amd64.tar.gz"
      sha256 "07abe8729c867025c9e0ec10be6c9ff9c89109d56abed228eb8eadf8e3a43794"

      def install
        bin.install "kj"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kitagry/kj/releases/download/0.3.1/kj_0.3.1_linux_arm64.tar.gz"
      sha256 "e3c8ce9e51465ada5932d1d70a3f940e847ccb4c0e615f120bd6a23c23f3b7dd"

      def install
        bin.install "kj"
      end
    end
  end
end
