# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kj < Formula
  desc "Edit and create Kubernetes job from cronjob template using your EDITOR"
  homepage "https://github.com/kitagry/kj"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kitagry/kj/releases/download/0.5.0/kj_0.5.0_Darwin_64bit.tar.gz"
      sha256 "dfdecd06a09b17a05806ef8d9c4df7a8cfda8884ad824415a3fd5da8a284a6a1"

      def install
        bin.install "kj"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kitagry/kj/releases/download/0.5.0/kj_0.5.0_Darwin_ARM64.tar.gz"
      sha256 "01886fa97cec33c27052c872c69394d86e57fe6404b5bdb2e4033009dab6455b"

      def install
        bin.install "kj"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kitagry/kj/releases/download/0.5.0/kj_0.5.0_Linux_64bit.tar.gz"
        sha256 "7b9a0db8479c46b6ae520c7b51f055d7a954e7bd3ee856372263e8ab4686cd68"

        def install
          bin.install "kj"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kitagry/kj/releases/download/0.5.0/kj_0.5.0_Linux_ARM64.tar.gz"
        sha256 "1bba4c362e6105b28e0c97917742a632f487595e5d6cabc1de20e7bdf76ac254"

        def install
          bin.install "kj"
        end
      end
    end
  end
end
