# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kj < Formula
  desc "Edit and create Kubernetes job from cronjob template using your EDITOR"
  homepage "https://github.com/kitagry/kj"
  version "0.4.0"

  on_macos do
    on_intel do
      url "https://github.com/kitagry/kj/releases/download/0.4.0/kj_0.4.0_Darwin_64bit.tar.gz"
      sha256 "224a8cbdf6c22b64cbcff7373252b044cd59465d823499d1f88d98a878ac9971"

      def install
        bin.install "kj"
      end
    end
    on_arm do
      url "https://github.com/kitagry/kj/releases/download/0.4.0/kj_0.4.0_Darwin_ARM64.tar.gz"
      sha256 "e0f80bb43371cbc19e6e0ef6dbb9c0c0aabaa0da2f583ffc03293a5b74d21639"

      def install
        bin.install "kj"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kitagry/kj/releases/download/0.4.0/kj_0.4.0_Linux_64bit.tar.gz"
        sha256 "76fd7e75883ceae7649258a628cb8a512106147789c09c9074845f219b18421b"

        def install
          bin.install "kj"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kitagry/kj/releases/download/0.4.0/kj_0.4.0_Linux_ARM64.tar.gz"
        sha256 "9e4cf544d56439d67b75564b4773e596f0c9fede249397432d0fd1a8834137e7"

        def install
          bin.install "kj"
        end
      end
    end
  end
end
