# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Regols < Formula
  desc "OPA Rego language server"
  homepage "https://github.com/kitagry/regols"
  version "0.2.4"

  on_macos do
    on_intel do
      url "https://github.com/kitagry/regols/releases/download/v0.2.4/regols_0.2.4_Darwin_64bit.tar.gz"
      sha256 "ac45c9516adb839f364d049bbc884952498cd4a061bf8ad9e6d42c2b59011c4e"

      def install
        bin.install "regols"
      end
    end
    on_arm do
      url "https://github.com/kitagry/regols/releases/download/v0.2.4/regols_0.2.4_Darwin_ARM64.tar.gz"
      sha256 "f30bee42812d5622e9f2f37b4627795ae8284ad44ef3e34ceb6db88d6769efe7"

      def install
        bin.install "regols"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kitagry/regols/releases/download/v0.2.4/regols_0.2.4_Linux_64bit.tar.gz"
        sha256 "42bcc37207d529cc33291df4113acc4447c01ae3a594ca3d440d96818e081fc0"

        def install
          bin.install "regols"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kitagry/regols/releases/download/v0.2.4/regols_0.2.4_Linux_ARM64.tar.gz"
        sha256 "950e6fbbb5145c13bab20ccd7fc9c7b8bb56741a17b63424a2657e5efdb13a59"

        def install
          bin.install "regols"
        end
      end
    end
  end
end
