# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Regols < Formula
  desc "OPA Rego language server"
  homepage "https://github.com/kitagry/regols"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kitagry/regols/releases/download/v0.2.2/regols_0.2.2_darwin_arm64.tar.gz"
      sha256 "d1bb4e4569d95ffb4b5783c12f445f78aac0337ea809fe60ad6b3558df33bb14"

      def install
        bin.install "regols"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kitagry/regols/releases/download/v0.2.2/regols_0.2.2_darwin_amd64.tar.gz"
      sha256 "64230a08d2514c3306e3a7c6d2c0acea819a7b543b5c8ba536e5f6593e615c84"

      def install
        bin.install "regols"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kitagry/regols/releases/download/v0.2.2/regols_0.2.2_linux_amd64.tar.gz"
      sha256 "1fbba0af62ed1f77c732f5972339a5a39a81e29df2fba3e1fb07302d02fab9ec"

      def install
        bin.install "regols"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kitagry/regols/releases/download/v0.2.2/regols_0.2.2_linux_arm64.tar.gz"
      sha256 "1afebe0ed9dacd4d5f4399d36c10a4b2190ea63d59a30be39e06e8e6652da285"

      def install
        bin.install "regols"
      end
    end
  end
end
